import { Router } from 'express';
import auth from '../middleware/auth.js';

import authRoutes from './auth.js';
import dashboardRoutes from './dashboard.js';

import businessRoutes from './business.js';
import calculationRoutes from './calculation.js';
import categoryRoutes from './category.js';
import certificateRoutes from './certificate.js';
import clarityRoutes from './clarity.js';
import collectionRoutes from './collection.js';
import colorRoutes from './color.js';
import customDutyRoutes from './customDuty.js';
import cutRoutes from './cut.js';
import cyclePeriodRoutes from './cyclePeriod.js';
import deliveryRoutes from './delivery.js';
import faqRoutes from './faq.js';
import hsnRoutes from './hsn.js';
import itemRoutes from './item.js';
import labelRoutes from './label.js';
import interestRoutes from './interest.js';
import makingChargeRoutes from './makingCharge.js';
import merchantRoutes from './merchant.js';
import metalRoutes from './metal.js';
import metalGroupRoutes from './metalGroup.js';
import offerRoutes from './offer.js';
import orderRoutes from './order.js';
import ornamentRoutes from './ornament.js';
import planRoutes from './plan.js';
import policyRoutes from './policy.js';
import productRoutes from './product.js';
import productTypeRoutes from './productType.js';
import referralRoutes from './referral.js';
import referralTypeRoutes from './referralType.js';
import refundRequestRoutes from './refundRequest.js';
import rejectReasonRoutes from './rejectReason.js';
import returnOrderRoutes from './returnOrder.js';
import reasonRoutes from './reason.js';
import roleRoutes from './role.js';
import sellRequestRoutes from './sellRequest.js';
import reserveRoutes from './reserve.js';
import settingRoutes from './setting.js';
import shapeRoutes from './shape.js';
import sliderRoutes from './slider.js';
import styleRoutes from './style.js';
import subscriptionRoutes from './subscription.js';
import supplierRoutes from './supplier.js';
import unitRoutes from './unit.js';
import userRoutes from './user.js';
import varietyRoutes from './variety.js';
import videoRoutes from './video.js';
import queueRoutes from './queue.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/queue', queueRoutes);
router.use('/', auth);

router.use('/dashboard', dashboardRoutes);

router.use('/business', businessRoutes);
router.use('/calculation', calculationRoutes);
router.use('/category', categoryRoutes);
router.use('/certificate', certificateRoutes);
router.use('/user', userRoutes);
router.use('/clarity', clarityRoutes);
router.use('/collection', collectionRoutes);
router.use('/colour', colorRoutes);
router.use('/customDuty', customDutyRoutes);
router.use('/cut', cutRoutes);
router.use('/cyclePeriod', cyclePeriodRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/faq', faqRoutes);
router.use('/hsn', hsnRoutes);
router.use('/item', itemRoutes);
router.use('/label', labelRoutes);
router.use('/interest', interestRoutes);
router.use('/makingCharge', makingChargeRoutes);
router.use('/merchant', merchantRoutes);
router.use('/metal', metalRoutes);
router.use('/metalGroup', metalGroupRoutes);
router.use('/offer', offerRoutes);
router.use('/order', orderRoutes);
router.use('/ornament', ornamentRoutes);
router.use('/plan', planRoutes);
router.use('/policy', policyRoutes);
router.use('/product', productRoutes);
router.use('/productType', productTypeRoutes);
router.use('/referral', referralRoutes);
router.use('/referralType', referralTypeRoutes);
router.use('/refundRequest', refundRequestRoutes);
router.use('/rejectReason', rejectReasonRoutes);
router.use('/returnOrder', returnOrderRoutes);
router.use('/reason', reasonRoutes);
router.use('/role', roleRoutes);
router.use('/sellRequest', sellRequestRoutes);
router.use('/reserve', reserveRoutes);
router.use('/setting', settingRoutes);
router.use('/shape', shapeRoutes);
router.use('/slider', sliderRoutes);
router.use('/style', styleRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/supplier', supplierRoutes);
router.use('/unit', unitRoutes);
router.use('/user', userRoutes);
router.use('/variety', varietyRoutes);
router.use('/video', videoRoutes);

export default router;
